### ISSUE TITLE
Unclear error

### ISSUE THREAD

**Issue by artgoldberg** [KarrLab/wc_utils#29]
This error was reported

    ../wc_utils/wc_utils/config/core.py:132: in get_config
        raise ExtraValuesError(value_sources, config)
    E   wc_utils.config.core.ExtraValuesError: The following configuration sources
    E     /root/host/Documents/wc_dev_repos/obj_model/obj_model/tests/config/core.default.cfg
    E     /root/.wc/obj_model.cfg
    E   
    E   contain the following configuration errors
    E     Extra entry in section 'top level'. Entry 'obj_model' is a section.

when `/root/host/Documents/wc_dev_repos/obj_model/obj_model/tests/config/core.default.cfg` did not exist. It would be clearer to report that error specifically.

**Comment by jonrkarr** [comment]
(1) Line 122 of `wc_utils/config.py` already checks that at least one of the possible config sources has configuration information. The file with the default values, `/root/host/Documents/wc_dev_repos/obj_model/obj_model/tests/config/core.default.cfg`, is not required to exist if there is config information provided by other files, the `extras` argument, or environmental variables.

(2) I have improved this error message so that files that don't exist aren't listed. The error message would now be the following:
```
The following configuration sources
  /root/.wc/obj_model.cfg
  
contain the following configuration errors
  Extra entry in section 'top level'. Entry 'obj_model' is a section.
```
(3) I have added more validation checking to resolve the source of the error and provide more specific error messages. With this change, each source of configuration data must be valid, even if its going to be overwritten.
